import type { ModelDefinition, StylePreset } from "@/lib/domain";

export const VIDEO_MODELS: ModelDefinition[] = [
  {
    id: "seedance-2-5",
    name: "Seedance 2.5",
    provider: "ByteDance / BytePlus",
    descriptionTh: "โมเดลหลักสำหรับงานเล่าเรื่องหลายช็อต ตัวละครต่อเนื่อง บทพูด และงานที่ใช้ Reference หลายชนิด",
    bestFor: ["Story", "Dialogue", "Multi-shot", "Character", "Anime", "Cinematic"],
    maxSecondsPerGeneration: 30,
    resolutions: ["480p", "720p"],
    supportsAudio: true,
    supportsImageReference: true,
    supportsVideoReference: true,
    supportsMultiShot: true,
    priceLevel: 2,
    enabled: true,
  },
  {
    id: "kling",
    name: "Kling",
    provider: "Kuaishou / Provider Adapter",
    descriptionTh: "เหมาะกับ Motion, Action, การเคลื่อนไหวซับซ้อน และช็อตที่ต้องการแรงปะทะของภาพ",
    bestFor: ["Action", "Motion", "Chase", "Combat"],
    maxSecondsPerGeneration: 15,
    resolutions: ["720p", "1080p"],
    supportsAudio: false,
    supportsImageReference: true,
    supportsVideoReference: true,
    supportsMultiShot: false,
    priceLevel: 2,
    enabled: true,
  },
  {
    id: "veo",
    name: "Veo",
    provider: "Google / Provider Adapter",
    descriptionTh: "เหมาะกับภาพสมจริง งาน Cinematic และฉากใหญ่ที่ต้องการรายละเอียดสิ่งแวดล้อมสูง",
    bestFor: ["Realistic", "Cinematic", "Environment", "Commercial"],
    maxSecondsPerGeneration: 8,
    resolutions: ["720p", "1080p"],
    supportsAudio: true,
    supportsImageReference: true,
    supportsVideoReference: false,
    supportsMultiShot: false,
    priceLevel: 3,
    enabled: true,
  },
  {
    id: "runway",
    name: "Runway",
    provider: "Runway / Provider Adapter",
    descriptionTh: "เหมาะกับงาน Creator, Motion Design และ Workflow ที่ต้องแก้ไขช็อตต่อเนื่อง",
    bestFor: ["Creator", "Motion", "Commercial", "Editorial"],
    maxSecondsPerGeneration: 10,
    resolutions: ["720p", "1080p"],
    supportsAudio: false,
    supportsImageReference: true,
    supportsVideoReference: true,
    supportsMultiShot: false,
    priceLevel: 3,
    enabled: true,
  },
  {
    id: "wan",
    name: "Wan",
    provider: "Alibaba / Provider Adapter",
    descriptionTh: "โมเดลทางเลือกแบบประหยัด เหมาะกับ B-roll, Preview และฉากที่ไม่ต้องการล็อกตัวละครเข้มมาก",
    bestFor: ["Economy", "Preview", "B-roll"],
    maxSecondsPerGeneration: 15,
    resolutions: ["480p", "720p"],
    supportsAudio: false,
    supportsImageReference: true,
    supportsVideoReference: false,
    supportsMultiShot: true,
    priceLevel: 1,
    enabled: true,
  },
];

const style = (
  id: string,
  nameTh: string,
  nameEn: string,
  category: string,
  descriptionTh: string,
  bestFor: string[],
  palette: string[],
  previewClass: string,
  prompt: string,
  negativePrompt = "inconsistent character, plastic CGI, random costume changes, flicker, text, watermark"
): StylePreset => ({ id, nameTh, nameEn, category, descriptionTh, bestFor, palette, previewClass, prompt, negativePrompt });

export const STYLE_PRESETS: StylePreset[] = [
  style("golden-anime", "อนิเมะแสงทอง", "Japanese Golden-Hour Anime", "Anime", "อนิเมะญี่ปุ่นโทนอุ่น แสงเย็นสีทอง ฉากหลังวาดมือ เหมาะกับเรื่องอบอุ่นและแฟนตาซีเบา ๆ", ["Slice of Life", "Fantasy", "Romance"], ["#f2d49b", "#d68d5e", "#66506f", "#211934"], "preview-golden", "cinematic Japanese anime storybook film, hand-painted suburban environment, warm golden-hour backlight, soft rim light, painterly textures, elegant animated-feature-film quality"),
  style("cinematic-anime", "อนิเมะภาพยนตร์", "Cinematic Anime", "Anime", "ภาพอนิเมะที่เน้นเลนส์ กล้อง แสง และมิติแบบภาพยนตร์", ["Drama", "Adventure", "Series"], ["#ab87ff", "#513a78", "#17121e"], "preview-purple", "high-end cinematic anime feature film, dimensional lighting, natural depth, restrained saturation, expressive faces, cinematic composition"),
  style("shonen-action", "อนิเมะแอ็กชัน", "Shonen Action Anime", "Action", "เหมาะกับการต่อสู้ วิ่งไล่ล่า พลังพิเศษ และการเคลื่อนไหวเร็ว", ["Fight", "Chase", "Power"], ["#ff7b55", "#5624c8", "#0d0c16"], "preview-action", "dynamic shonen action anime, readable choreography, strong silhouettes, cinematic impact frames, controlled motion blur, dramatic directional lighting"),
  style("scifi-anime", "อนิเมะไซไฟ", "Sci-Fi Anime", "Sci-Fi", "โลกอนาคต หุ่นยนต์ ยานอวกาศ เมืองเทคโนโลยี และแสงโฮโลแกรม", ["Mecha", "Future", "Space"], ["#56d9ff", "#7b4dff", "#15142d"], "preview-cyber", "cinematic sci-fi anime, futuristic city, holographic interfaces, advanced technology, deep atmospheric perspective, elegant luminous accents"),
  style("mecha", "เมคคะ", "Mecha Cinema", "Sci-Fi", "เน้นหุ่นยนต์ขนาดใหญ่ เครื่องจักร โลหะหนัก และสเกลมหากาพย์", ["Mecha", "War", "Epic"], ["#9da8bb", "#372965", "#0c0f16"], "preview-mecha", "epic cinematic mecha film, monumental scale, detailed mechanical joints, realistic weight, volumetric atmosphere, dramatic low-angle photography"),
  style("cyberpunk", "ไซเบอร์พังก์", "Neon Cyberpunk", "Sci-Fi", "เมืองอนาคตกลางคืน ป้ายไฟ เทคโนโลยี และบรรยากาศล้ำยุค", ["Future City", "Thriller", "Action"], ["#00e6ff", "#ec4cff", "#111021"], "preview-neon", "premium cyberpunk cinema, dense futuristic city, neon reflections, rain-slick surfaces, holographic signage, cinematic haze"),
  style("space-opera", "มหากาพย์อวกาศ", "Space Opera", "Sci-Fi", "ยานอวกาศ ดาวเคราะห์ สงครามอวกาศ และภาพสเกลใหญ่", ["Space", "Epic", "Adventure"], ["#312d70", "#f39a54", "#070812"], "preview-space", "epic space opera, vast star fields, monumental spacecraft, planetary scale, cinematic volumetric lighting, dramatic cosmic composition"),
  style("cinematic-real", "สมจริงแบบภาพยนตร์", "Cinematic Realistic", "Realistic", "ภาพสมจริงที่เน้นเลนส์ แสง และเกรดสีแบบภาพยนตร์", ["Short Film", "Commercial", "Drama"], ["#d5b27b", "#54616f", "#111214"], "preview-real", "cinematic photoreal film frame, natural skin, practical lighting, filmic color science, subtle grain, realistic optics, believable depth"),
  style("luxury-commercial", "โฆษณาพรีเมียม", "Luxury Commercial", "Commercial", "เหมาะกับสินค้า แฟชั่น รถยนต์ และงานแบรนด์ระดับพรีเมียม", ["Product", "Fashion", "Brand"], ["#e2d4b8", "#7b5d4a", "#101010"], "preview-luxury", "luxury commercial film, precise product lighting, premium materials, elegant camera motion, high-end art direction"),
  style("dark-fantasy", "ดาร์กแฟนตาซี", "Dark Fantasy", "Fantasy", "โลกแฟนตาซีหม่น ปราสาท ป่าลึกลับ หมอก และเวทมนตร์", ["Magic", "Mystery", "Epic"], ["#48505d", "#4a3266", "#111119"], "preview-dark", "dark fantasy cinema, ancient environments, mysterious fog, moonlit atmosphere, painterly realism, magical particles, dramatic silhouettes"),
  style("soft-fantasy", "แฟนตาซีนุ่มละมุน", "Soft Fantasy", "Fantasy", "โทนฝัน อ่อนโยน แสงนุ่ม เหมาะกับภูต สัตว์วิเศษ และนิทาน", ["Creature", "Fairy", "Kids"], ["#dbc4ff", "#f8d9df", "#7d6f9a"], "preview-soft", "soft fantasy storybook film, dreamy natural light, delicate pastel atmosphere, whimsical creatures, handcrafted painterly texture"),
  style("horror", "สยองขวัญภาพยนตร์", "Cinematic Horror", "Horror", "แสงน้อย ความกดดัน เงามืด และองค์ประกอบที่สร้างความไม่สบายใจ", ["Horror", "Suspense", "Mystery"], ["#352c3d", "#66535a", "#09090c"], "preview-horror", "cinematic horror, motivated low-key lighting, ominous negative space, restrained camera, psychological tension, realistic shadows"),
  style("noir", "ฟิล์มนัวร์", "Film Noir", "Cinematic", "เงาจัด แสงเฉียง คอนทราสต์สูง เหมาะกับสืบสวนและอาชญากรรม", ["Crime", "Mystery", "Drama"], ["#d8d8d8", "#686868", "#111111"], "preview-noir", "film noir cinema, hard directional light, venetian blind shadows, monochrome tonal range, smoky atmosphere, classic composition"),
  style("warm-slice", "ชีวิตประจำวันอบอุ่น", "Cozy Slice of Life", "Emotional", "เรียบง่าย อบอุ่น เป็นธรรมชาติ เหมาะกับครอบครัว มิตรภาพ และ Coming-of-age", ["Family", "Friendship", "Coming of Age"], ["#f6dfbc", "#d69b8b", "#8b8068"], "preview-cozy", "cozy slice-of-life film, soft natural daylight, intimate framing, subtle expressions, gentle color palette, lived-in environments"),
  style("rainy-mood", "บรรยากาศวันฝนตก", "Rainy Mood", "Emotional", "ฝน กระจกเปียก แสงสะท้อน และอารมณ์เหงาแบบภาพยนตร์", ["Drama", "Romance", "Memory"], ["#5f7890", "#333e54", "#121724"], "preview-rain", "cinematic rainy atmosphere, wet reflections, soft blue-gray light, window droplets, restrained melancholic mood"),
  style("kids-3d", "การ์ตูน 3D สำหรับเด็ก", "Kids 3D Cartoon", "3D", "ตัวละครน่ารัก รูปทรงอ่านง่าย สีอ่อน และการเคลื่อนไหวเป็นมิตร", ["Kids", "Education", "Mascot"], ["#ffbfcc", "#91d8ff", "#f9e7a8"], "preview-kids", "premium stylized 3D animated film, friendly proportions, soft materials, warm lighting, clean readable shapes, expressive but natural animation"),
  style("storybook", "นิทานภาพวาด", "Painterly Storybook", "Illustration", "พื้นผิวเหมือนวาดมือ สีอ่อน และความรู้สึกเหมือนหนังสือนิทานมีชีวิต", ["Kids", "Fantasy", "Narration"], ["#e7c99c", "#98a57e", "#765b69"], "preview-story", "hand-painted storybook animation, visible brush texture, poetic composition, soft natural light, handcrafted imperfections"),
  style("post-apoc", "โลกหลังล่มสลาย", "Post-Apocalyptic Cinema", "Sci-Fi", "เมืองร้าง ฝุ่น ควัน ซากอาคาร และความรู้สึกเอาตัวรอด", ["Survival", "Action", "Sci-Fi"], ["#9b876e", "#665e51", "#1b1a18"], "preview-apoc", "post-apocalyptic cinematic world, ruined infrastructure, dust-filled atmosphere, grounded survival realism, harsh sunlight, cinematic scale"),
  style("tactical-scifi", "แอ็กชันไซไฟยุทธวิธี", "Tactical Sci-Fi Action", "Action", "ชุดเกราะ เทคโนโลยีสนามรบ ทีมปฏิบัติการ และกล้องแอ็กชันที่อ่านการเคลื่อนไหวชัด", ["Combat", "Exosuit", "Future War"], ["#556c73", "#7b53e4", "#0f1215"], "preview-tactical", "tactical sci-fi action cinema, advanced armor, readable squad blocking, grounded weapon motion, practical futuristic technology, cinematic battle lighting"),
  style("martial-arts", "ศิลปะการต่อสู้", "Martial Arts Cinema", "Action", "เน้นท่าต่อสู้ การเคลื่อนไหวร่างกาย และกล้องที่มองเห็น choreography ชัด", ["Fight", "Martial Arts", "Action"], ["#d6b074", "#703733", "#111111"], "preview-martial", "cinematic martial arts choreography, full-body readability, controlled tracking camera, realistic momentum, impact without chaotic editing"),
  style("music-video", "มิวสิกวิดีโอ", "Music Video", "Creator", "ภาพมีจังหวะ แสงสร้างอารมณ์ และการเคลื่อนกล้องสัมพันธ์กับเพลง", ["Music", "Performance", "Social"], ["#c64cff", "#4056ff", "#111020"], "preview-music", "premium music video cinematography, rhythmic camera movement, expressive lighting, editorial composition, polished performance visuals"),
  style("fashion", "แฟชั่นเอดิทอเรียล", "Fashion Editorial", "Commercial", "ภาพแฟชั่นคม เรียบ หรู เน้นชุด ท่าทาง และการจัดแสง", ["Fashion", "Beauty", "Brand"], ["#f0e9e3", "#75646e", "#111111"], "preview-fashion", "high-fashion editorial film, sculpted soft light, elegant poses, premium fabric detail, minimal luxury art direction"),
  style("documentary", "สารคดีภาพยนตร์", "Documentary Film", "Cinematic", "เป็นธรรมชาติ ดูจริง ไม่ปรุงมาก เหมาะกับเรื่องชีวิตและสารคดี", ["Documentary", "Human", "Travel"], ["#cbbd9d", "#6a716e", "#20211f"], "preview-doc", "cinematic documentary realism, observational camera, available light, natural motion, authentic environments, restrained grading"),
];

export const CAMERA_HELP = {
  shotTypes: [
    ["Extreme Wide Shot", "ภาพกว้างมาก", "เน้นสถานที่และสเกล ตัวละครมีขนาดเล็ก เหมาะกับฉากเปิดเรื่องหรือโลกขนาดใหญ่"],
    ["Wide Shot", "ภาพกว้าง", "เห็นตัวละครเต็มตัวพร้อมสิ่งแวดล้อม เหมาะกับการเดิน วิ่ง และ Action"],
    ["Full Shot", "ภาพเต็มตัว", "เห็นศีรษะถึงเท้า เน้นท่าทาง เสื้อผ้า และการเคลื่อนไหว"],
    ["Medium Shot", "ภาพครึ่งตัว", "เห็นประมาณเอวขึ้นไป เหมาะกับบทสนทนาและการแสดง"],
    ["Close-up", "ภาพใกล้", "เน้นใบหน้าและอารมณ์ของตัวละคร"],
    ["Extreme Close-up", "ภาพใกล้มาก", "เน้นรายละเอียด เช่น ดวงตา มือ หรือวัตถุสำคัญ"],
    ["POV", "มุมมองสายตาตัวละคร", "ให้ผู้ชมเห็นสิ่งที่ตัวละครกำลังมอง"],
    ["Over-the-Shoulder", "มุมข้ามไหล่", "เหมาะกับบทสนทนาและการเชื่อมสายตาระหว่างสองตัวละคร"],
    ["Insert Shot", "ภาพแทรกรายละเอียด", "เน้นวัตถุหรือข้อมูลเล็ก ๆ ที่สำคัญต่อเรื่อง"],
  ],
  angles: [
    ["Eye Level", "ระดับสายตา", "ให้ความรู้สึกธรรมชาติ เป็นกลาง"],
    ["Low Angle", "มุมต่ำ", "กล้องมองขึ้น ทำให้ตัวละครดูทรงพลังหรือโดดเด่น"],
    ["Extreme Low Angle", "มุมต่ำมาก", "กล้องเกือบติดพื้น เหมาะกับ Action สัตว์ตัวเล็ก หรือสเกลใหญ่"],
    ["High Angle", "มุมสูง", "กล้องมองลง ทำให้ตัวละครดูเล็กหรือเปราะบาง"],
    ["Top View", "มองจากด้านบน", "แสดงตำแหน่งและองค์ประกอบทั้งพื้นที่"],
    ["Side View", "มุมด้านข้าง", "เหมาะกับการเดิน วิ่ง หรือการต่อสู้ด้านข้าง"],
    ["Rear View", "มุมด้านหลัง", "ให้ความรู้สึกติดตามตัวละครหรือเดินทางไปข้างหน้า"],
    ["Three-quarter View", "มุมเฉียงสามส่วน", "เห็นหน้าและด้านข้างพร้อมกัน ทำให้ตัวละครมีมิติ"],
  ],
  movements: [
    ["Static", "กล้องนิ่ง", "ใช้เมื่ออยากให้ผู้ชมโฟกัสการแสดงหรือองค์ประกอบภาพ"],
    ["Push-in", "ค่อย ๆ เข้าใกล้", "เพิ่มความสนใจ อารมณ์ หรือความตึงเครียด"],
    ["Pull-out", "ค่อย ๆ ถอยออก", "เปิดเผยสถานที่หรือใช้เป็นภาพจบ"],
    ["Tracking", "ติดตามตัวละคร", "เหมาะกับเดิน วิ่ง ไล่ล่า และสำรวจสถานที่"],
    ["Dolly", "เคลื่อนกล้องบนแนวตรง", "ให้การเคลื่อนกล้องลื่นแบบภาพยนตร์"],
    ["Pan", "หมุนซ้ายหรือขวา", "ติดตามวัตถุหรือเปิดเผยสิ่งที่อยู่นอกเฟรม"],
    ["Tilt", "เงยหรือก้ม", "เผยความสูงหรือเชื่อมองค์ประกอบบน-ล่าง"],
    ["Crane", "เคลื่อนกล้องขึ้นลง", "เหมาะกับฉากใหญ่ การเปิดหรือปิด Sequence"],
    ["Orbit", "หมุนรอบตัวละคร", "เน้นตัวละครหรือช่วงพิเศษ แต่ควรใช้เท่าที่จำเป็น"],
    ["Whip Pan", "สะบัดกล้องเร็ว", "เหมาะกับ Action และการเปลี่ยนจุดสนใจเร็ว"],
    ["Lateral Slide", "เลื่อนด้านข้าง", "สร้าง Parallax และเหมาะกับช็อตแอบมองผ่านสิ่งกีดขวาง"],
  ],
};

export const LENS_HELP = [
  [18, "กว้างมาก", "เหมาะกับสถาปัตยกรรม ฉากใหญ่ และ Action ใกล้กล้อง"],
  [24, "กว้างแบบภาพยนตร์", "เหมาะกับ Establishing Shot และมุมต่ำ"],
  [28, "กว้างธรรมชาติ", "ยังเห็นสิ่งแวดล้อมมากแต่บิดเบือนน้อยลง"],
  [35, "เป็นธรรมชาติและมีฉาก", "เหมาะกับ Tracking, Street Scene และตัวละครเต็มตัว"],
  [50, "ใกล้สายตามนุษย์", "เหมาะกับบทสนทนาและ Medium Shot"],
  [65, "เน้นตัวละคร", "เหมาะกับ Medium Close-up และ Reaction"],
  [85, "Portrait / Close-up", "เน้นใบหน้า ฉากหลังละลายและดึงอารมณ์"],
  [100, "รายละเอียดสูง", "เหมาะกับ Extreme Close-up หรือวัตถุสำคัญ"],
] as const;
