export type CinematicCoveragePreset = {
  id: string;
  category: "dialogue" | "action" | "suspense" | "drama" | "cinematic" | "narrative";
  nameTh: string;
  nameEn: string;
  descriptionTh: string;
  instruction: string;
};

export const CINEMATIC_COVERAGE_PRESETS: CinematicCoveragePreset[] = [
  { id: "shot-reverse-shot", category: "dialogue", nameTh: "สนทนาตัดสลับหน้า", nameEn: "Shot / Reverse Shot", descriptionTh: "สลับ Close-up ตัวละคร A/B พร้อม Reaction และรักษา eyeline", instruction: "Build classic shot/reverse-shot coverage with a stable 180-degree axis, matching eyelines, reaction inserts, and return to established camera slots." },
  { id: "intimate-conversation", category: "dialogue", nameTh: "บทสนทนาใกล้ชิด", nameEn: "Intimate Conversation", descriptionTh: "เริ่ม Medium แล้วค่อยเข้า Close-up เมื่ออารมณ์ลึกขึ้น", instruction: "Start with shared medium coverage, progressively move into singles and close-ups as emotion intensifies, preserving screen direction and eye-line continuity." },
  { id: "tense-interrogation", category: "dialogue", nameTh: "สอบสวนกดดัน", nameEn: "Tense Interrogation", descriptionTh: "สลับ OTS, CU และ insert มือ/วัตถุเพื่อเพิ่มแรงกดดัน", instruction: "Use opposing over-the-shoulders, controlled close-ups, detail inserts, and reaction holds. Maintain a clear power axis and increasingly tighter framing." },
  { id: "argument-escalation", category: "dialogue", nameTh: "ทะเลาะเดือดขึ้นเรื่อยๆ", nameEn: "Argument Escalation", descriptionTh: "มุมเริ่มนิ่งแล้วถี่และใกล้ขึ้นตามอารมณ์", instruction: "Escalate from stable two-shot to faster singles, close-ups and reaction cuts. Keep blocking coherent and do not cross the axis without a motivated re-establishing shot." },
  { id: "emotional-confession", category: "dialogue", nameTh: "สารภาพความรู้สึก", nameEn: "Emotional Confession", descriptionTh: "เน้นหน้า สายตา การหยุดหายใจ และ reaction ของอีกฝ่าย", instruction: "Prioritize performance close-ups, eye-line matches, breathing pauses, subtle reaction cutaways and a final shared frame that resolves emotional distance." },

  { id: "pursuit-cross-cut", category: "action", nameTh: "ไล่ล่าตัดสลับ", nameEn: "Pursuit Cross-Cut", descriptionTh: "ตัดสลับผู้ไล่กับผู้หนีและกลับมามุมเดิมอย่างต่อเนื่อง", instruction: "Cross-cut pursuer and target with recurring camera slots, matching direction of travel, inserts of obstacles, and cut-on-action transitions while preserving geography." },
  { id: "fight-coverage", category: "action", nameTh: "ต่อสู้หลายมุม", nameEn: "Fight Coverage", descriptionTh: "Master, Medium, Impact CU และ Reaction โดยไม่หลุดตำแหน่ง", instruction: "Use a master for geography, medium action coverage, impact close-ups, reaction shots and inserts. Preserve left/right positions, movement vectors and prop continuity." },
  { id: "ambush-reveal", category: "action", nameTh: "ซุ่มโจมตีแล้วเปิดเผย", nameEn: "Ambush Reveal", descriptionTh: "เริ่มมุมปลอดภัย ก่อนเผยภัยจากมุมซ่อนและตัดกลับ reaction", instruction: "Begin with calm subject coverage, introduce hidden observer/POV angles, reveal the ambush, then cross-cut reactions and action while maintaining spatial anchors." },
  { id: "escape-reaction", category: "action", nameTh: "หนี + Reaction", nameEn: "Escape & Reaction", descriptionTh: "สลับมุมการหนี ทางข้างหน้า และสีหน้าตัวละคร", instruction: "Alternate forward motion, rear tracking, obstacle POV and reaction close-ups. Keep travel direction consistent and use foreground wipes or cut-on-action for seamless edits." },
  { id: "hero-entrance", category: "action", nameTh: "เปิดตัวฮีโร่", nameEn: "Hero Entrance", descriptionTh: "เริ่มรายละเอียด → silhouette → full reveal → reaction คนรอบข้าง", instruction: "Stage a reveal sequence from detail insert to silhouette, low-angle hero reveal, reaction cutaways, then a confident master shot with consistent light direction." },

  { id: "creature-encounter", category: "suspense", nameTh: "เผชิญสิ่งมีชีวิตแบบหนัง", nameEn: "Creature Encounter Cross-Cut", descriptionTh: "แบบคลิปตัวอย่าง: ตัวละคร → POV ซ่อน → สิ่งมีชีวิต → reaction → กลับมามุมเดิม", instruction: "Use recurring subject and creature camera slots, hidden observer POV, creature reveal close-up, over-the-shoulder spatial relation, low-angle creature inserts, reaction close-ups, occlusion transitions and re-establishing wides." },
  { id: "stalker-pov", category: "suspense", nameTh: "มุมผู้เฝ้ามอง", nameEn: "Stalker POV", descriptionTh: "ตัดระหว่างตัวละครกับ POV ที่แอบมองผ่านฉากหน้า", instruction: "Cross-cut normal subject coverage with voyeur POV through foreground occlusion. Reuse the same observer slot and maintain exact subject screen direction and distance." },
  { id: "hidden-observer", category: "suspense", nameTh: "ผู้สังเกตซ่อนตัว", nameEn: "Hidden Observer", descriptionTh: "ใช้ใบไม้ ประตู เสา หรือเงาบังเฟรมเพื่อสร้างความรู้สึกถูกจับตา", instruction: "Use layered foreground occlusion, long-lens observer shots, subject reaction inserts and recurring hidden camera positions. Preserve location geometry and sight lines." },
  { id: "doorway-reveal", category: "suspense", nameTh: "เปิดเผยผ่านประตู/กำแพง", nameEn: "Doorway Reveal", descriptionTh: "ใช้ประตูหรือกำแพงเป็น transition ซ่อนรอยตัด", instruction: "Design doorway, wall or pillar reveals with motivated camera moves, occlusion cuts and return angles that preserve axis, screen direction and lighting continuity." },
  { id: "horror-reaction-loop", category: "suspense", nameTh: "สยองตัด Reaction วนกลับ", nameEn: "Horror Reaction Loop", descriptionTh: "ภัย → หน้าเหยื่อ → ภัยใกล้ขึ้น → หน้าเหยื่อ → reveal", instruction: "Build a threat/reaction/threat/reaction escalation loop, reusing stable threat and victim camera slots while progressively tightening framing and preserving eyelines." },

  { id: "discovery-reaction", category: "drama", nameTh: "ค้นพบแล้ว Reaction", nameEn: "Discovery Reaction", descriptionTh: "เห็นสิ่งสำคัญ → insert → reaction → กลับไปสิ่งนั้น", instruction: "Use subject POV, detail insert, reaction close-up and return-to-object framing. Match eyelines and maintain exact object location between cuts." },
  { id: "reunion", category: "drama", nameTh: "พบกันอีกครั้ง", nameEn: "Reunion Coverage", descriptionTh: "Wide ระยะห่าง → Singles → เข้าใกล้ → Shared frame", instruction: "Show initial distance in a master, alternate emotional singles, track the approach, then resolve into a shared frame while preserving direction and wardrobe continuity." },
  { id: "betrayal-reveal", category: "drama", nameTh: "เฉลยการหักหลัง", nameEn: "Betrayal Reveal", descriptionTh: "ข้อมูลใหม่ → สีหน้า → ฝ่ายตรงข้าม → insert หลักฐาน → reaction", instruction: "Structure reveal information through evidence insert, betrayer single, victim reaction, return to evidence and final two-shot. Keep screen geography and prop identity locked." },
  { id: "grief-isolation", category: "drama", nameTh: "ความเศร้าและโดดเดี่ยว", nameEn: "Grief & Isolation", descriptionTh: "Wide เวิ้งว้างสลับกับรายละเอียดและใบหน้า", instruction: "Contrast isolated wide frames with intimate face and hand inserts. Use slow restrained moves and maintain consistent light direction and spatial loneliness." },
  { id: "decision-moment", category: "drama", nameTh: "ช่วงตัดสินใจ", nameEn: "Decision Moment", descriptionTh: "POV ตัวเลือก → reaction → detail → กลับหน้า → action", instruction: "Alternate POV options, reaction close-up, decisive detail insert and action follow-through, preserving eyelines and object positions." },

  { id: "master-medium-close", category: "cinematic", nameTh: "Master → Medium → Close", nameEn: "Classic Coverage Ladder", descriptionTh: "ชุดมาตรฐานหนัง: Establish, Medium, Close, Reaction, Wide", instruction: "Build a classic coverage ladder: establishing master, medium action, close-up story beat, reaction, insert and re-establishing master. Reuse camera slots coherently." },
  { id: "dynamic-orbit-cutaways", category: "cinematic", nameTh: "Orbit + Cutaway", nameEn: "Dynamic Orbit & Cutaways", descriptionTh: "เคลื่อนกล้องรอบตัวแบบมีเหตุผล สลับ cutaway ไม่เวียนหัว", instruction: "Use one motivated arc/orbit shot supported by cutaways and reaction singles. Do not orbit randomly; preserve axis awareness and return to stable anchor shots." },
  { id: "foreground-wipe", category: "cinematic", nameTh: "Foreground Wipe", nameEn: "Foreground Occlusion Transitions", descriptionTh: "คน/เสา/กำแพงผ่านหน้าเลนส์เพื่อซ่อนรอยตัด", instruction: "Place foreground objects or characters across frame to motivate hidden cuts and angle changes, keeping action and light continuity seamless across the wipe." },
  { id: "match-cut", category: "cinematic", nameTh: "Match Cut", nameEn: "Match-Cut Sequence", descriptionTh: "จับคู่รูปทรง การเคลื่อนไหว หรือ framing ระหว่างช็อต", instruction: "Design match cuts using shape, gaze, movement or composition. Keep the narrative readable and preserve identity and spatial continuity around matched transitions." },
  { id: "cinematic-handheld", category: "cinematic", nameTh: "Handheld แบบควบคุม", nameEn: "Controlled Handheld", descriptionTh: "ให้ความรู้สึกอยู่ในเหตุการณ์แต่ยังดูแพงและอ่านภาพง่าย", instruction: "Use restrained handheld movement for immediacy, alternating stable anchors and reaction shots. Avoid random shake, maintain screen direction and readable blocking." },

  { id: "establish-detail-return", category: "narrative", nameTh: "Establish → Detail → กลับ Wide", nameEn: "Establish / Detail / Return", descriptionTh: "เปิดโลก → เจาะข้อมูลสำคัญ → กลับมารวมความสัมพันธ์", instruction: "Open with geography, cut into key details and reactions, then return to the master to confirm spatial relationships and story progression." },
  { id: "parallel-action", category: "narrative", nameTh: "เหตุการณ์คู่ขนาน", nameEn: "Parallel Action", descriptionTh: "สลับเหตุการณ์ A/B ที่เกิดพร้อมกันโดยรักษาทิศและเวลา", instruction: "Cross-cut parallel actions with clear recurring camera slots, time progression and distinct but coherent spatial anchors. Keep each thread easy to recognize." },
  { id: "character-ab-crosscut", category: "narrative", nameTh: "ตัวละคร A ↔ B", nameEn: "Character A/B Cross-Cut", descriptionTh: "สลับตัวละครสองฝั่งและกลับมามุมเดิมได้อย่างต่อเนื่อง", instruction: "Assign stable A and B camera slots, alternate based on story information and reactions, preserve matching eyelines and screen direction, and re-establish when needed." },
  { id: "three-character-triangle", category: "narrative", nameTh: "สามตัวละครแบบ Triangle", nameEn: "Three-Character Triangle", descriptionTh: "จัดแกนสายตาสามคนโดยไม่ทำให้ผู้ชมสับสน", instruction: "Define a clear triangle of screen positions and eyelines for three characters, use singles/OTS/two-shots, and never cross the action axis without a motivated reset." },
  { id: "twist-ending", category: "narrative", nameTh: "ตอนจบหักมุม", nameEn: "Twist Ending Coverage", descriptionTh: "ปูข้อมูล → reaction → reveal → กลับไปอ่านความหมายใหม่", instruction: "Plant visual information, hold reaction coverage, reveal the twist with a motivated angle or insert, then return to a familiar shot whose meaning has changed." },
];

export function cinematicCoveragePreset(id: string | null | undefined) {
  return CINEMATIC_COVERAGE_PRESETS.find((preset) => preset.id === id) || CINEMATIC_COVERAGE_PRESETS[10]!;
}
