import type { Project } from "@/lib/domain";

export const SAMPLE_PROJECT: Project = {
  id: "project-scenova-demo",
  title: "เด็กหญิงกับสัตว์จากแสงจันทร์",
  story: "เด็กหญิงเดินกลับบ้านในซอยญี่ปุ่นช่วงแสงเย็น เธอรู้สึกว่ามีบางอย่างกำลังมองอยู่ ก่อนพบสัตว์วิเศษตัวเล็กที่ค่อย ๆ กล้าเข้ามาหา ทั้งสองเริ่มต้นมิตรภาพประหลาดโดยสื่อสารผ่านสายตาและท่าทาง",
  genre: "Nostalgic Slice-of-Life Fantasy",
  mood: "อบอุ่น สงบ อยากรู้อยากเห็น น่ารัก และลึกลับเล็กน้อย",
  aspectRatio: "9:16",
  episodeCount: 5,
  mainModelId: "seedance-2-5",
  modelMode: "single",
  promptMode: "assisted",
  resolution: "720p",
  styleId: "golden-anime",
  locks: {
    project: true,
    character: true,
    style: true,
    voice: true,
    location: true,
    prop: true,
    canon: true,
    camera: true,
    lighting: true,
    motion: true,
    model: true,
  },
  projectBible: "โลกปัจจุบันในย่านชานเมืองญี่ปุ่นที่ดูปกติ แต่มีสิ่งมีชีวิตวิเศษซ่อนอยู่ในพื้นที่เงียบ ๆ โทนหลักเป็นช่วงเย็นฤดูร้อน ความสัมพันธ์ของเด็กหญิงและสัตว์วิเศษพัฒนาอย่างค่อยเป็นค่อยไป ไม่ใช้ความรุนแรงใน EP แรก",
  canon: [
    "GIRL_A ยังไม่เคยพบ MOON_CREATURE_A ก่อน EP.01",
    "MOON_CREATURE_A ขี้อายและจะไม่เข้าหามนุษย์อย่างรวดเร็ว",
    "กระเป๋าสีชมพูและกิ๊บดอกไม้เป็นลักษณะประจำตัวของ GIRL_A",
  ],
  characters: [
    {
      id: "GIRL_A",
      name: "GIRL_A",
      kind: "human",
      description: "เด็กหญิงอนิเมะรูปร่างเล็กตามธรรมชาติ ผิวขาวอุ่น ดวงตาสีน้ำตาลเทาเงานุ่ม บุคลิกเงียบ อ่อนโยน และอยากรู้อยากเห็น",
      appearance: "ผมดำอมน้ำตาลมัดมวยสูงยุ่งเล็กน้อย หน้าม้าบาง เส้นผมข้างแก้ม กิ๊บดอกไม้สีชมพูหม่นห้ากลีบ",
      outfit: "ฮู้ดดี้โอเวอร์ไซซ์สีครีม กระโปรงพลีทสั้นสีเทาถ่าน เลกวอร์มเมอร์สีงาช้าง รองเท้าขาวนวล กระเป๋าเป้ชมพูหม่นตรากระต่ายและพวงห้อยกระต่าย",
      personality: "สงบ อ่อนโยน ช่างสังเกต ไม่แสดงสีหน้าเกินจริง",
      voiceProfile: "soft-young-female-th",
      lock: true,
      references: [
        { id: "girl-front", label: "หน้าตรง", kind: "front" },
        { id: "girl-full", label: "เต็มตัว", kind: "full-body" },
        { id: "girl-side", label: "ด้านข้าง", kind: "side" },
      ],
    },
    {
      id: "MOON_CREATURE_A",
      name: "MOON_CREATURE_A",
      kind: "creature",
      description: "สัตว์วิเศษตัวเล็กทรงกลมคล้ายตุ๊กตา ขนนุ่มสีน้ำเงินกรมท่าและม่วงน้ำเงิน ดวงตากลมโตสีน้ำตาลเข้ม",
      appearance: "หูยาวใหญ่ รูปทรงไม่สมมาตรเล็กน้อย ปอยผมเกลียวสีลาเวนเดอร์ตรงหน้าผาก แก้มชมพู หางกลมฟู",
      outfit: "จี้กระดิ่งทรงกลมทองเหลืองโบราณ มีช่องรูปดาวห้าแฉกด้านหน้า",
      personality: "ไร้เดียงสา ขี้อาย อยากรู้อยากเห็น และประหม่าเล็กน้อย",
      lock: true,
      references: [
        { id: "moon-front", label: "หน้าตรง", kind: "front" },
        { id: "moon-full", label: "เต็มตัว", kind: "full-body" },
      ],
    },
  ],
  episodes: [
    {
      id: "ep-01",
      number: 1,
      title: "ใครอยู่ตรงนั้น?",
      duration: 30,
      synopsis: "GIRL_A เดินกลับบ้านและพบ MOON_CREATURE_A เป็นครั้งแรก",
      status: "ready",
      segments: [
        {
          id: "ep01-seg01",
          start: 0,
          end: 10,
          title: "เดินกลับบ้าน",
          scene: "GIRL_A เดินไปตามซอยญี่ปุ่นเงียบ ๆ ในแสงเย็น ก่อนเริ่มรู้สึกว่ามีบางอย่างมองอยู่",
          location: "Japanese suburban alley",
          characterIds: ["GIRL_A"],
          action: "เดินช้าอย่างเป็นธรรมชาติ กระเป๋าและพวงห้อยแกว่งตามการเคลื่อนไหว จากนั้นชะลอฝีเท้าเล็กน้อย",
          emotion: "สงบ → สงสัยเล็กน้อย",
          lighting: "late-afternoon golden hour, warm amber backlight, dappled leaf shadows",
          sound: "เสียงลมเบา ๆ นกไกล ๆ และเสียงรองเท้าบนพื้น ไม่มีบทพูด",
          cameraShots: [
            {
              id: "cam-01",
              start: 0,
              end: 5,
              shotType: "Extreme Wide Shot",
              angle: "Extreme Low Angle / Rear View",
              lensMm: 24,
              cameraHeight: "20 ซม. จากพื้น",
              movement: "Dolly",
              movementSpeed: "ช้ามาก",
              focus: "GIRL_A และ vanishing point",
              depthOfField: "Deep environmental depth",
              composition: "Centered subject, strong leading lines, large negative space",
              foregroundOcclusion: "ไม่มี",
            },
            {
              id: "cam-02",
              start: 5,
              end: 10,
              shotType: "Medium Wide Shot",
              angle: "Low Angle / Rear View",
              lensMm: 35,
              cameraHeight: "ต่ำกว่าระดับเอว",
              movement: "Tracking",
              movementSpeed: "ช้าและลื่น",
              focus: "GIRL_A full body and backpack",
              depthOfField: "Medium depth",
              composition: "Rear follow with architectural parallax",
              foregroundOcclusion: "เงาใบไม้บางส่วน",
            },
          ],
          dialogue: [],
        },
        {
          id: "ep01-seg02",
          start: 10,
          end: 20,
          title: "สายตาที่ซ่อนอยู่",
          scene: "GIRL_A หยุดและหันมอง ก่อนตัดไปเห็น MOON_CREATURE_A แอบอยู่หลังใบไม้",
          location: "Japanese suburban alley / leafy wall",
          characterIds: ["GIRL_A", "MOON_CREATURE_A"],
          action: "GIRL_A หันศีรษะอย่างช้า ๆ; creature จับกระดิ่งและมองขึ้นอย่างประหม่า",
          emotion: "สงสัย / ขี้อาย",
          lighting: "golden rim light with warm-versus-cool shaded foliage",
          sound: "เสียงใบไม้ไหวเบา ๆ ไม่มีบทพูด",
          cameraShots: [
            {
              id: "cam-03",
              start: 10,
              end: 15,
              shotType: "Medium Close-up",
              angle: "Three-quarter View",
              lensMm: 65,
              cameraHeight: "ระดับอก",
              movement: "Push-in",
              movementSpeed: "ช้ามาก",
              focus: "GIRL_A eyes",
              depthOfField: "Shallow",
              composition: "Face on upper third, backpack edge remains visible",
              foregroundOcclusion: "ไม่มี",
            },
            {
              id: "cam-04",
              start: 15,
              end: 20,
              shotType: "Extreme Close-up",
              angle: "Eye Level",
              lensMm: 85,
              cameraHeight: "ระดับสายตาของ creature",
              movement: "Static",
              movementSpeed: "เกือบนิ่ง",
              focus: "MOON_CREATURE_A eyes and bell",
              depthOfField: "Extremely shallow",
              composition: "Leaves create a natural frame around the face",
              foregroundOcclusion: "ใบไม้เบลอหน้ากล้อง",
            },
          ],
          dialogue: [],
        },
        {
          id: "ep01-seg03",
          start: 20,
          end: 30,
          title: "เริ่มต้นมิตรภาพ",
          scene: "MOON_CREATURE_A วิ่งข้ามทาง GIRL_A เดินตามและชะโงกมองรอบมุม ก่อนจบด้วยภาพกว้างของทั้งสอง",
          location: "Japanese suburban alley / old residential gate",
          characterIds: ["GIRL_A", "MOON_CREATURE_A"],
          action: "creature วิ่งด้วยก้าวเล็กและหูเด้งตามแรง; GIRL_A เดินตามอย่างระมัดระวังแล้วอมยิ้ม",
          emotion: "ประหลาดใจ → เป็นมิตร",
          lighting: "consistent warm golden-hour backlight",
          sound: "เสียงกระดิ่งเบา ๆ เสียงเท้าและลม ไม่มีบทพูด",
          cameraShots: [
            {
              id: "cam-05",
              start: 20,
              end: 25,
              shotType: "Wide Shot",
              angle: "Extreme Low Angle / Side View",
              lensMm: 28,
              cameraHeight: "10 ซม. จากพื้น",
              movement: "Tracking",
              movementSpeed: "เร็วแต่ลื่น",
              focus: "MOON_CREATURE_A motion",
              depthOfField: "Medium",
              composition: "Strong lateral motion and parallax",
              foregroundOcclusion: "ไม่มี",
            },
            {
              id: "cam-06",
              start: 25,
              end: 30,
              shotType: "Extreme Wide Shot",
              angle: "Extreme Low Angle",
              lensMm: 24,
              cameraHeight: "ใกล้พื้น",
              movement: "Pull-out",
              movementSpeed: "ช้ามาก",
              focus: "ทั้งสองตัวละครในระยะไกล",
              depthOfField: "Deep",
              composition: "Large negative space, quiet environmental ending",
              foregroundOcclusion: "กำแพงและเสาไฟช่วยแบ่งเฟรม",
            },
          ],
          dialogue: [],
        },
      ],
    },
  ],
};
