import type { ProductionChoice } from "@/lib/production-options";

export const VOICE_PROFILES = [
  "Mira — หญิง Adult อบอุ่น เป็นธรรมชาติ",
  "Nami — หญิง Young สดใส เป็นกันเอง",
  "Sora — หญิง Adult สุขุม หรูหรา",
  "Vela — หญิง Adult เข้มแข็ง มั่นใจ",
  "Arin — ชาย Adult สุขุม ภาพยนตร์",
  "Keen — ชาย Adult หนักแน่น แอ็กชัน",
  "Noah — ชาย Young นุ่ม เป็นธรรมชาติ",
  "Orin — ชาย Senior ลุ่มลึก น่าเชื่อถือ",
  "Lumi — Teen สดใส Coming-of-age",
  "Kai — Teen เป็นกันเอง มีพลัง",
  "Narrator Calm — ผู้บรรยาย สุขุม สารคดี",
  "Narrator Epic — ผู้บรรยาย หนักแน่น Trailer",
  "Astra AI — เสียงสังเคราะห์ Sci-Fi สุขุม",
  "Nyx Character — ตัวละครลึกลับ Fantasy / Villain",
];

export const AMBIENCE_PRESETS: ProductionChoice[] = [
  { value: "Room Tone", label: "Room Tone — เสียงพื้นห้อง", help: "เสียงพื้นเบามากของสถานที่ภายใน ช่วยให้ฉากไม่เงียบผิดธรรมชาติ" },
  { value: "Ocean Waves", label: "Ocean Waves — คลื่นทะเล", help: "เสียงคลื่นต่อเนื่อง เหมาะกับชายหาด รีสอร์ต และฉากริมทะเล" },
  { value: "Gentle Shore", label: "Gentle Shore — คลื่นชายฝั่งเบา", help: "คลื่นนุ่มและลมทะเล เหมาะกับ Romance และฉากสงบ" },
  { value: "River Flow", label: "River Flow — แม่น้ำไหล", help: "เสียงน้ำไหลต่อเนื่อง เหมาะกับธรรมชาติ หมู่บ้าน และฉากพักอารมณ์" },
  { value: "Forest Stream", label: "Forest Stream — ลำธารในป่า", help: "น้ำไหลเล็ก ๆ ผสมเสียงป่า ให้ความรู้สึกสดชื่นและเป็นธรรมชาติ" },
  { value: "Waterfall", label: "Waterfall — น้ำตก", help: "น้ำแรงต่อเนื่อง เหมาะกับฉากธรรมชาติขนาดใหญ่และ Fantasy" },
  { value: "Light Rain", label: "Light Rain — ฝนเบา", help: "ฝนตกนุ่ม ๆ ใช้สร้าง Mood สงบ เหงา หรือโรแมนติก" },
  { value: "Heavy Rain", label: "Heavy Rain — ฝนหนัก", help: "ฝนหนาแน่นและกระทบพื้นชัด เหมาะกับ Drama, Thriller และฉากกลางพายุ" },
  { value: "Thunderstorm", label: "Thunderstorm — พายุฝนฟ้าคะนอง", help: "ฝน ลม และฟ้าร้องต่อเนื่อง เพิ่มแรงกดดันให้ฉาก" },
  { value: "Soft Wind", label: "Soft Wind — ลมเบา", help: "ลมอ่อนในพื้นที่เปิด เหมาะกับทุ่ง ภูเขา ชายหาด และฉากสงบ" },
  { value: "Strong Wind", label: "Strong Wind — ลมแรง", help: "ลมพัดหนัก เพิ่มความรู้สึกหนาว อันตราย หรือสภาพอากาศรุนแรง" },
  { value: "Leaves Rustling", label: "Leaves Rustling — ใบไม้ไหว", help: "เสียงใบไม้จากลม เหมาะกับสวน ป่า และบ้านชนบท" },
  { value: "Forest Day", label: "Forest Day — ป่ากลางวัน", help: "นก ลม ใบไม้ และเสียงธรรมชาติกลางวัน" },
  { value: "Forest Night", label: "Forest Night — ป่ากลางคืน", help: "แมลง ลม และเสียงธรรมชาติกลางคืน เหมาะกับ Mystery / Horror" },
  { value: "Birds Morning", label: "Birds Morning — เสียงนกยามเช้า", help: "ช่วยบอกช่วงเวลาและทำให้ฉากเช้าดูมีชีวิต" },
  { value: "Night Insects", label: "Night Insects — แมลงกลางคืน", help: "จิ้งหรีดและแมลงเบา ๆ สำหรับชนบท ป่า และฉากกลางคืน" },
  { value: "City Day", label: "City Day — เมืองกลางวัน", help: "รถ ผู้คน และกิจกรรมเมืองในระยะกลาง/ไกล" },
  { value: "City Night", label: "City Night — เมืองกลางคืน", help: "รถไกล ๆ ผู้คนบางส่วน และเสียงเมืองที่เบาลง" },
  { value: "Traffic", label: "Traffic — การจราจร", help: "รถยนต์ มอเตอร์ไซค์ และถนน เหมาะกับฉากริมถนนหรือในเมือง" },
  { value: "Busy Market", label: "Busy Market — ตลาดคึกคัก", help: "คนพูดคุย ร้านค้า และกิจกรรมจำนวนมาก" },
  { value: "Cafe Interior", label: "Cafe Interior — บรรยากาศร้านกาแฟ", help: "บทสนทนาไกล ๆ เครื่องชงกาแฟ จานแก้ว และ Room Tone" },
  { value: "Airport Terminal", label: "Airport Terminal — สนามบิน", help: "เสียงผู้โดยสาร ประกาศ และพื้นที่โถงขนาดใหญ่" },
  { value: "Train Station", label: "Train Station — สถานีรถไฟ", help: "รถไฟ ผู้โดยสาร ประกาศ และเสียงสถานี" },
  { value: "Air Conditioner", label: "Air Conditioner — เครื่องปรับอากาศ", help: "เสียงฮัมคงที่สำหรับสำนักงาน โรงแรม ห้องเรียน และอาคาร" },
  { value: "Crowd Murmur", label: "Crowd Murmur — เสียงฝูงชนไกล ๆ", help: "เสียงผู้คนรวมกันโดยไม่แยกคำ เหมาะกับงาน Event และสถานที่สาธารณะ" },
  { value: "Sci-Fi Hum", label: "Sci-Fi Hum — เสียงเครื่องจักรอนาคต", help: "เสียงระบบไฟและเครื่องจักรคงที่สำหรับยาน ห้องทดลอง และสถานีอวกาศ" },
  { value: "Spaceship Interior", label: "Spaceship Interior — ภายในยานอวกาศ", help: "เครื่องยนต์เบา ระบบระบายอากาศ และอุปกรณ์อิเล็กทรอนิกส์" },
  { value: "Horror Room Tone", label: "Horror Room Tone — บรรยากาศกดดัน", help: "Drone ต่ำและเสียงห้องบาง ๆ สำหรับ Thriller / Horror" },
  { value: "Silence", label: "Silence — เงียบโดยตั้งใจ", help: "ใช้ช่วงเงียบเพื่อเน้น Reaction, Reveal หรือ Moment สำคัญ" },
];

export const SFX_PRESETS: ProductionChoice[] = [
  { value: "None", label: "None — ยังไม่ใส่ SFX", help: "ใช้เมื่อฉากยังไม่มีเหตุการณ์เสียงเฉพาะ" },
  { value: "Car Pass", label: "Car Pass — รถวิ่งผ่าน", help: "เสียงรถผ่านจากด้านหนึ่งไปอีกด้าน เหมาะกับถนนและเมือง" },
  { value: "Engine Start", label: "Engine Start — สตาร์ทรถ", help: "ใช้ตรงจังหวะตัวละครเปิดรถหรือเริ่มเคลื่อนที่" },
  { value: "Motorcycle Pass", label: "Motorcycle Pass — มอเตอร์ไซค์ผ่าน", help: "เสียงยานพาหนะที่เด่นและเคลื่อนเร็วกว่า Traffic ปกติ" },
  { value: "Train Pass", label: "Train Pass — รถไฟวิ่งผ่าน", help: "เสียงรถไฟขนาดใหญ่ เหมาะกับสถานี ทางรถไฟ และฉาก Transition" },
  { value: "Footsteps", label: "Footsteps — ฝีเท้า", help: "เสียงเดินหรือวิ่ง ควรสัมพันธ์กับพื้น รองเท้า และจังหวะตัวละคร" },
  { value: "Door Open", label: "Door Open — เปิดประตู", help: "เสียงเปิดประตูตามวัสดุและน้ำหนักของประตู" },
  { value: "Door Close", label: "Door Close — ปิดประตู", help: "ใช้เป็นจังหวะ Action หรือเน้นการจบ Beat" },
  { value: "Knock", label: "Knock — เคาะประตู", help: "เสียงเคาะที่สามารถกำหนดจำนวนครั้งและความแรงตามอารมณ์" },
  { value: "Phone Notification", label: "Phone Notification — แจ้งเตือนโทรศัพท์", help: "ใช้กับข้อความ การโทร หรือข้อมูลใหม่ในฉาก" },
  { value: "Keys", label: "Keys — กุญแจ", help: "เสียงหยิบ หมุน หรือเขย่ากุญแจสำหรับ Foley รายละเอียด" },
  { value: "Cloth Rustle", label: "Cloth Rustle — เสียงเสื้อผ้า", help: "Foley เบา ๆ ตามการขยับตัว นั่ง ลุก หรือเดิน" },
  { value: "Glass Break", label: "Glass Break — กระจกแตก", help: "เสียงกระจกแตกสำหรับ Action / Accident / Thriller" },
  { value: "Impact", label: "Impact — เสียงกระแทก", help: "เสียงกระแทกทั่วไปสำหรับวัตถุ ชน หรือ Action Beat" },
  { value: "Explosion", label: "Explosion — ระเบิด", help: "เสียงระเบิดเชิงภาพยนตร์ ใช้ตามเหตุการณ์ในฉาก" },
  { value: "Sword Clash", label: "Sword Clash — ดาบปะทะ", help: "เสียงโลหะปะทะสำหรับ Fantasy / Historical Action" },
  { value: "Debris", label: "Debris — เศษวัสดุตก", help: "เสียงเศษหิน ไม้ หรือโลหะตกหลังแรงกระแทก" },
  { value: "Water Splash", label: "Water Splash — น้ำกระเซ็น", help: "ใช้กับการเดินลงน้ำ วัตถุตกน้ำ หรือคลื่นกระแทก" },
  { value: "Wave Crash", label: "Wave Crash — คลื่นซัดแรง", help: "เสียงคลื่นกระแทกเฉพาะจังหวะ ต่างจาก Ocean Ambience ที่เป็นเสียงต่อเนื่อง" },
  { value: "Thunder Crack", label: "Thunder Crack — ฟ้าร้องฉับพลัน", help: "เสียงฟ้าร้องเฉพาะจังหวะสำหรับเน้น Beat หรือสภาพอากาศ" },
  { value: "Whoosh", label: "Whoosh — เสียงหวือเปลี่ยนจังหวะ", help: "ใช้กับการเคลื่อนเร็ว Transition หรือ Motion Graphic" },
  { value: "Cinematic Hit", label: "Cinematic Hit — เสียงกระแทกภาพยนตร์", help: "เน้น Reveal, Title, Cut หรือ Moment สำคัญ" },
  { value: "Cinematic Riser", label: "Cinematic Riser — เสียงไต่ระดับ", help: "เพิ่มแรงส่งก่อน Reveal, Action หรือ Turning Point" },
  { value: "Magic Pulse", label: "Magic Pulse — พลังเวท", help: "เสียงพลังงานแฟนตาซีสำหรับคาถา วัตถุเวท และสิ่งมีชีวิต" },
  { value: "Portal", label: "Portal — ประตูมิติ", help: "เสียงเปิด/ปิดมิติสำหรับ Fantasy และ Sci-Fi" },
  { value: "Robot Servo", label: "Robot Servo — กลไกหุ่นยนต์", help: "เสียงมอเตอร์และข้อต่อสำหรับ Robot / Mecha" },
];

export const MUSIC_PRESETS: ProductionChoice[] = [
  { value: "None", label: "None — ไม่ใช้ดนตรี", help: "ให้ Dialogue, Ambience และ SFX ทำหน้าที่ทั้งหมด" },
  { value: "Emotional Piano", label: "Emotional Piano — เปียโนอารมณ์", help: "เหมาะกับ Drama, Romance, Memory และฉากที่เน้นความรู้สึก" },
  { value: "Suspense Drone", label: "Suspense Drone — เสียงดนตรีกดดัน", help: "เหมาะกับ Mystery, Thriller และฉากรอการเปิดเผย" },
  { value: "Action Pulse", label: "Action Pulse — จังหวะแอ็กชัน", help: "จังหวะต่อเนื่องสำหรับ Chase, Combat และการเร่งความเร็วของเรื่อง" },
  { value: "Fantasy Orchestra", label: "Fantasy Orchestra — ออร์เคสตราแฟนตาซี", help: "ใช้กับ Adventure, Epic Fantasy และการเปิดโลกขนาดใหญ่" },
  { value: "Sci-Fi Atmosphere", label: "Sci-Fi Atmosphere — ดนตรีบรรยากาศไซไฟ", help: "Texture อิเล็กทรอนิกส์สำหรับโลกอนาคตและอวกาศ" },
];
